//
//  LoginPresenter.swift
//  CleanSwiftExample
//
//  Created by Yoni Vizel on 10/30/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    func presentLogin(response: Login.Login.Response)
}

class LoginPresenter: LoginPresentationLogic {
    weak var viewController: LoginDisplayLogic?

    // MARK: Parse and calc respnse from LoginInteractor and send simple view model to LoginViewController to be displayed

    func presentLogin(response: Login.Login.Response) {
        let username = response.user.name
        let age = response.user.age
        let viewModel = Login.Login.ViewModelSuccess(username: username, age: age)
        viewController?.displayUser(viewModel: viewModel)
    }
}
