//
//  LoginViewController.swift
//  CleanSwiftExample
//
//  Created by Yoni Vizel on 10/30/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginDisplayLogic: class
{
    func displayUser(viewModel: Login.Login.ViewModelSuccess)
    func displayFailure(viewModel: Login.Login.ViewModelFailure)
}

class LoginViewController: UIViewController, LoginDisplayLogic {

    private enum Segue: String {
        case homeSegue
    }

    var interactor: LoginBusinessLogic?
    var router: (NSObjectProtocol & LoginRoutingLogic)?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        modalPresentationStyle = .fullScreen
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        modalPresentationStyle = .fullScreen
        setup()
    }
            
    // MARK: - Setup Clean Code Design Pattern 

    private func setup() {
        let viewController = self
        let interactor = LoginInteractor()
        let presenter = LoginPresenter()
        let router = LoginRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
    }
   
    //MARK: - receive events from UI
    
    @IBAction func loginButtonTapped(_ sender: Any) {
        login()
    }

    // MARK: - request data from LoginInteractor

    func login() {
        let request = Login.Login.Request(username: "Captain Jack Sparrow", password: "123456")
        interactor?.login(request: request)
    }

    // MARK: - display view model from LoginPresenter

    func displayUser(viewModel: Login.Login.ViewModelSuccess) {
        performSegue(withIdentifier: Segue.homeSegue.rawValue, sender: self)
    }

    func displayFailure(viewModel: Login.Login.ViewModelFailure) {
        // display error message
    }
}
